//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace curdopeartionmvc
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public int EmployeeId { get; set; }
        public string Fristname { get; set; }
        public string Lastname { get; set; }
        public string Mobilenumber { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DateofJoining { get; set; }
        public Nullable<System.DateTime> DateOfBrith { get; set; }
        public string Qualification { get; set; }
        public string Department { get; set; }
    }
}
